// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Guilherme-DSGL/purchase_transaction_backend/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// IExchangeRepository is an autogenerated mock type for the IExchangeRepository type
type IExchangeRepository struct {
	mock.Mock
}

// GetExchange provides a mock function with given fields: ctx, exchangedParams
func (_m *IExchangeRepository) GetExchange(ctx context.Context, exchangedParams *entities.ExchangeRequestParams) (entities.ExchangeTransaction, error) {
	ret := _m.Called(ctx, exchangedParams)

	if len(ret) == 0 {
		panic("no return value specified for GetExchange")
	}

	var r0 entities.ExchangeTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ExchangeRequestParams) (entities.ExchangeTransaction, error)); ok {
		return rf(ctx, exchangedParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ExchangeRequestParams) entities.ExchangeTransaction); ok {
		r0 = rf(ctx, exchangedParams)
	} else {
		r0 = ret.Get(0).(entities.ExchangeTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.ExchangeRequestParams) error); ok {
		r1 = rf(ctx, exchangedParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExchangeRepository creates a new instance of IExchangeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExchangeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExchangeRepository {
	mock := &IExchangeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
