// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Guilherme-DSGL/purchase_transaction_backend/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// IExchangeService is an autogenerated mock type for the IExchangeService type
type IExchangeService struct {
	mock.Mock
}

// GetExchange provides a mock function with given fields: ctx, exchangeParams
func (_m *IExchangeService) GetExchange(ctx context.Context, exchangeParams *entities.ExchangeGetParams) {
	_m.Called(ctx, exchangeParams)
}

// NewIExchangeService creates a new instance of IExchangeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExchangeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExchangeService {
	mock := &IExchangeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
