// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Guilherme-DSGL/vr_exchange_backend/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// IExchangeService is an autogenerated mock type for the IExchangeService type
type IExchangeService struct {
	mock.Mock
}

// GetExchange provides a mock function with given fields: ctx, exchangeParams
func (_m *IExchangeService) GetExchange(ctx context.Context, exchangeParams *entities.ExchangeGetParams) (entities.ExchangeTransaction, error) {
	ret := _m.Called(ctx, exchangeParams)

	if len(ret) == 0 {
		panic("no return value specified for GetExchange")
	}

	var r0 entities.ExchangeTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ExchangeGetParams) (entities.ExchangeTransaction, error)); ok {
		return rf(ctx, exchangeParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.ExchangeGetParams) entities.ExchangeTransaction); ok {
		r0 = rf(ctx, exchangeParams)
	} else {
		r0 = ret.Get(0).(entities.ExchangeTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.ExchangeGetParams) error); ok {
		r1 = rf(ctx, exchangeParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIExchangeService creates a new instance of IExchangeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExchangeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExchangeService {
	mock := &IExchangeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
